services:
  - type: web
    name: injury-prediction-app
    env: python
    buildCommand: pip install --upgrade pip setuptools && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

